language: android
jdk: openjdk8
os: linux

before_install:
  - chmod +x gradlew

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script: ./gradlew clean lint
    - stage: test
      script: ./gradlew clean test

after_success:
  - ./gradlew jacocoTestReportDebug coveralls
