language: android
jdk: openjdk8
os: linux

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29

jobs:
  include:
    - stage: "Lint, test and coverage report"
      script: ./gradlew lint jacocoTestReportDebug

after_success:
  - ./gradlew coveralls
