language: android
jdk: openjdk8
os: linux


env:
  - COVERALLS_REPO_TOKEN=12ebf32f5a3702432c23fe15640b5b6361baf0d9
  - CI_NAME=travis-ci

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29

before_install:
  - chmod +x gradlew

after_success:
  - ./gradlew jacocoTestReportDebug coveralls
