language: android
jdk: openjdk8
os: linux

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29

before_install:
  - chmod +x gradlew

jobs:
  include:
    - stage: "Lint"
      script: ./gradlew lint
    - stage: "Test"
      script: ./gradlew test

after_success:
  - ./gradlew jacoco coveralls
