language: android
jdk: openjdk8
os: linux

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29

env:
  - COVERALLS_REPO_TOKEN=12ebf32f5a3702432c23fe15640b5b6361baf0d9
  - CI_NAME=travis-ci

before_install:
  - chmod +x gradlew

jobs:
  include:
    - stage: "Lint, test and coverage report"
      script: ./gradlew lint jacocoTestReportDebug

after_success:
  - ./gradlew coveralls
