language: android
jdk: oraclejdk8
os: linux

before_install:
  - chmod +x gradlew

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
#    - sys-img-armeabi-v7a-android-16

#script:
#  ./gradlew runUnitTests